name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Lint client
      working-directory: ./client
      run: npm run lint
    
    - name: Install server dependencies
      working-directory: ./server
      run: |
        pip install -r requirements.txt
        pip install flake8 black mypy
    
    - name: Lint server
      working-directory: ./server
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install and test client
      working-directory: ./client
      run: |
        npm ci
        npm test
    
    - name: Install and test server
      working-directory: ./server
      run: |
        pip install -r requirements.txt
        pytest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Build client
      working-directory: ./client
      run: |
        npm ci
        npm run build
    
    - name: Upload client artifacts
      uses: actions/upload-artifact@v3
      with:
        name: client-build
        path: client/.next

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'CRITICAL,HIGH'
